version: '3.9'

services:
  fsapi:
    image: salmonllama/fashionscape-api:latest
    restart: always
    environment:
      PG_URI:
      PG_PORT:
      PG_USER:
      PG_PASS:
      PG_DB:
    ports:
      - "8888:8888"
    container_name: fashionscape-api

